
services:
    mongo_client:
      class:       MongoDB\Client
      arguments:  ['mongodb://root:auNgooqu7E@storage:27017']
    graphql_api:
      class:       App\GraphQLSchema\Api
      arguments:  ['@mongo_client']
    graphql_middleware:
        class:     App\RequestHandler\Middleware\GraphQLMiddleware
        arguments: ['@graphql_api']
    authentication_middleware:
        class:     App\RequestHandler\Middleware\Authorization
